### ISSUE TITLE
Detection error

### ISSUE THREAD

**Issue by adcoolguy** [svenanders/react-iframe#4]
Is there any way currently otherwise any plan in the future to support / handle error of iframe loading better? For example, we have error such as: "Refused to display 'https://www.facebook.com/user.1683628638/posts/10153731529787012' in a frame because it set 'X-Frame-Options' to 'DENY'."

Thanks for any reply/workaround!

**Comment by svenanders** [comment]
Will investigate! 
Youtube videos work if you pass in embed in URL, for instance http://www.youtube.com/embed/xDMP3i36naA instead of http://www.youtube.com/xDMP3i36naA

**Comment by ffugly** [comment]
+1 Refused to display 'https://www.google.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

**Comment by svenanders** [comment]
I'm not sure there's a way around it, or whether one should even try. This is a policy the websites use to prevent "clickjacking" and/or to prevent anyone from embedding google.com (for instance) into a page full of ads, and to save traffic.

**Comment by ffugly** [comment]
Fair enough. Are you able to throw a callback if the page renders an error like this though?

**Comment by svenanders** [comment]
I'm going to investigate it a bit further, but it seems there's no good options but verifying it manually. One suggestion was to make an AJAX-request and inspect the X-Frame header (http://stackoverflow.com/questions/25411408/how-to-check-if-a-page-is-allowed-to-be-iframed) but you're very likely to get a huge number of false positives because you'll run into CORS issues even on pages that allow iframes (eg. example.com and youtube).
